[tox]
envlist=
    lint
    mypy
    docs
    covclean
    py{38,39,310,311,312,313,314},pypy
    covcombine
    covreport
labels =
    ci = py,covcombine,covreport

[testenv]
passenv = CI
extras = dev
deps =
    coverage
    py{38,39,310}-toml: tomli
setenv = PYTHONPATH={toxinidir}
commands =
    !mp: coverage run nose2 -v --pretty-assert {posargs}
    mp: coverage run nose2 -v --plugin nose2.plugins.mp -N 0 {posargs}

depends =
    py{,py,38,39,310,311,312,313,314}{,-mp,-toml}: covclean
    covcombine: py{,py,38,39,310,311,312,313,314}{,-mp,-toml}
    covreport: covcombine

[testenv:covclean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:covcombine]
deps = coverage
skip_install = true
commands = coverage combine

[testenv:covreport]
deps = coverage
skip_install = true
commands_pre = coverage html --fail-under=0
commands = coverage report

[testenv:lint]
deps = pre-commit~=4.4.0
skip_install = true
commands = pre-commit run --all-files

[testenv:mypy]
extras = dev
deps =
    mypy==1.10.0
    types-setuptools
    types-docutils
    tomli
    coverage
commands =
    mypy nose2/ {posargs}

[testenv:docs]
extras = dev
changedir = docs
commands = sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv:build]
deps =
    build
    twine
skip_install = true
allowlist_externals = rm
commands_pre = rm -rf dist/
commands =
    python -m build
    twine check dist/*

[testenv:publish]
deps = twine
skip_install = true
commands = twine upload dist/*
